### ISSUE TITLE
Request:  Array of fields to return

### ISSUE THREAD

**Issue by corepay** [Mattchewone/feathers-shallow-populate#15]
Thank you for making and publishing this hook.  Saved me a ton of time and head scratching trying to other hooks and code to fetch associated data.

Have a request if you think worthy.  How about an array on the target include that allows us to specify which fields to return?  My postgres is a quite complex multi-tenant with a lot of relationships and useless associations and other fields that in these associations that is not relevant to the the response I need to return to the app.

I can discard the unnecessary data  in an after hook but in my case would need to update and maintain 80+ tables - this option would save a ton of time and makes sense re: efficiency and compressing the response....

Whaddyathink?

```
const options = {
  include: {
    service: 'phones',
    nameAs: 'phone',
    keyHere: 'default_phone_id',
    keyThere: 'id'
    fields: ['name', 'number', 'extension', 'e164']     <-------- this
  }
}
```

**Comment by corepay** [comment]
Oh...@marshall I see you are one of the maintainers.  Was going to mention I am using feathers-vuex on client with `setupInstance`, so assume that the service `id` should be returned be default...si?

**Comment by marshallswain** [comment]
Yeah, I'm the primary maintainer on this, now. The id would definitely require to be returned.

**Comment by corepay** [comment]
@marshallswain great!  appreciate your efforts in community.

 So what do you think about the request to provide an array of fields to return?

**Comment by marshallswain** [comment]
Since FeathersJS already has a query operator for `$select`, maybe it would make sense to update `feathers-shallow-populate` to allow you customize the `params` object.  We could make it so the `params` attribute in each `include` could be a function that receives the params object AFTER feathers-shallow-populate has already built the query.`

```js
{
  params: (params) => {
    params.query.$select = ['name', 'number', 'extension', 'e164']
  }
}
```

**Comment by marshallswain** [comment]
@corepay you can now customize the params, based on the work by @fratzinger in #16.  Check out the updated docs in the readme.  You'll need to install `feathers-shallow-populate@2.1.0`.

**Comment by corepay** [comment]
Works great!  This helps a lot, makes a few related hacks less hacky.

Thank you @fratzinger and @marshallswain !
