### ISSUE TITLE
ability for more complicated relations

### ISSUE THREAD

**Issue by fratzinger** [Mattchewone/feathers-shallow-populate#18]
I love this library for its simplicity, but I stumbled upon the need to define more complex relations which cannot be defined with `keyHere` and `keyThere`. Instead I can customize the query with the `params` option, for sure.
So I would to change the code a little bit, which insists on `keyThere` and `keyHere`. This is totally necessary for most cases, of course. I would like to change it, like so:

```
//pseudocode
const isDynamicInclude = (include) => {
  const { params } = include
  return params && (!_isEmpty(params) || params instanceof Function);
}
if (include(isDynamicInclude)) {
  assertKeyHereKeyThere();
} else {
  skipKeyHereKeyThere();
}
```

This issue is more of a reminder for me to test this out, but maybe someone has thoughts on that. Hopefully I will come to this within the next days. I guess it's not that easy because of the dataMap.

**Comment by aliciahogue** [comment]
Somehow having the ability to provide a "through" table would be awesome, allowing just the associated records to be returned rather then the cross reference table record, with a child record of the item...   I was also thinking at one point that paramsHere and paramsThere would be useful

**Comment by fratzinger** [comment]
Please have a look at my PR for further information :) Feel free to share your thoughts on my code :)
